### PR TITLE
Update .NET-version

### PR DESCRIPTION
**Pull request by kleivane**
Update notnet version in readme, dotnet 8 is required is it not?

.NET 6.0 has end of support November 12, 2024

### CODE REVIEW

**Comment by martinothamar** [comment]
Yeah we should, there is an issue on it here: https://github.com/Altinn/app-localtest/issues/2
It will involve updating projects and dependencies, base docker image etc..

**Comment by kleivane** [comment]
I might be misunderstanding but, this readme is for running Altinn apps locally? We followed the readme yesterday with a new developer without a prior who installed .NET 6 as pr the docs and it failed demanding an upgrade to 8. After installing .NET8, it all went smooth. So I just thought the readme needed an update for new developers? 

The issue #2 is about updating the dockerimage for localtest?

**Comment by martinothamar** [comment]
Oh, I see, yeah so running localtest (the code in this repository) doesn't even require .NET as it runs inside a container runtime. The .NET/Altinn version of your app dictates which version of .NET should be used. v7 of the backend targets .NET 6 while v8 targets .NET 8. So I guess we could make the doc here more precise

**Comment by martinothamar** [comment]
So essentially this one is a bit more descriptive: https://github.com/Altinn/app-localtest/pull/109

**Pull request closed without merging**
