### PR TITLE
Support any version in Index.cshtml when replacing frontend version

### LINKED ISSUE #77: Support app-frontend v4 when replacing frontend version
The code to replace the frontend version at runtime does not work correctly when `Index.cshtml` uses any other path than `/3/`. We should at least support `/4/`, but it would be even better to support any pinned version of frontend.

### PR DESCRIPTION
**Pull request by bjosttveit**
## Description

This adds support for replacing any frontend version in `Index.cshtml`. Unfortunately, this was a bit more involved than expected, since the standard `sub_filter` only allows simple string substitution and not regex. To get around this, I needed the third-party [ngx_http_substitutions_filter_module](https://www.nginx.com/resources/wiki/modules/substitutions/). This required some modifications to the standard docker image for nginx which I based on [this](https://github.com/tofran/nginx-with-substitutions-filter-docker).

This also fixes a bug where it would not find the frontendVersion cookie if it was the last one in the `Cookies` header. This is because it previously required the string to end with a `;`. This probably explains the flakyness I myself have experienced with this before.

## Related Issue(s)
- closes #77 

## Verification
- [x] **Your** code builds clean without any errors or warnings
- [x] Manual testing done (required)

### CODE REVIEW

**Review by olemartinorg — APPROVED** [review]
Looks good to me! :partying_face:

**Review by ivarne — APPROVED** [review]
You seem to have found an even more complicated way to keep the nginx proxy (wrongly named `loadbalancer`) working even further beyond what it nginx is supposed to do.

You have my approval, but maybe we should look into reviving https://github.com/ivarne/altinn-studio/commit/6e6b2e255bb7346b2ba2dbd9c9a1f0c8c024b4fa (and bug fix from https://github.com/ivarne/altinn-studio/commit/eb9353ff33be61ba6da990499b3afbd35c64d281) instead. Would be nice if docker/podman wasn't a requirement for local testing of apps that don't need to generate pdfs.

**Comment by bjosttveit** [comment]
Sounds like a good idea to get rid of nginx @ivarne, this is indeed an overcomplicated way to do this 😅 

Should I still merge this as a short term fix? And then maybe we should create an issue to look into rewriting the proxy feature?

**Comment by ivarne** [comment]
> Should I still merge this as a short term fix?

Yes, That is what an approval with no positive comment means. If it works and is better than what we have, it is ready for merge.

**Pull request merged**
